-- Add is_ai_generated column to daily_recaps table
ALTER TABLE daily_recaps 
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT false;

-- Add comment to explain the column
COMMENT ON COLUMN daily_recaps.is_ai_generated IS 'Indicates whether the recap was generated by AI (true) or manually edited by user (false)';

